name: Daily Auto Push

on:
  schedule:
    - cron: '0 9,15,21 * * *'
  workflow_dispatch:

# Forzamos Node 24 a nivel de todo el proceso
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Esto ayuda a evitar problemas de permisos en algunos runners
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar script
        run: python daily_push.py

      - name: Commit y Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add log.txt```